services:
  glms-backend-api:
    build:
      context: .
      dockerfile: GLMS.API/Dockerfile
    container_name: glms_api
    ports:
      - "7001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    networks:
      - glms_network

  glms-frontend-web:
    build:
      context: .
      dockerfile: GLMS/Dockerfile
    container_name: glms_mvc
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - glms-backend-api
    networks:
      - glms_network

  sql-server-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: glms_sql_server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - glms_network

networks:
  glms_network:
    driver: bridge

volumes:
  sql_data: