// <auto-generated />
using System;
using GLMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GLMS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260422150934_InitialCreate2")]
    partial class InitialCreate2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GLMS.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            Address = "123 Main St, Johannesburg",
                            ContactPerson = "John Doe",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "contact@globalimporters.com",
                            Name = "Global Importers Ltd",
                            Phone = "+27 11 234 5678",
                            Region = "Africa"
                        },
                        new
                        {
                            ClientId = 2,
                            Address = "45 Berliner Str, Berlin",
                            ContactPerson = "Anna Schmidt",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "info@eurotech.eu",
                            Name = "EuroTech Solutions",
                            Phone = "+49 30 1234 5678",
                            Region = "Europe"
                        },
                        new
                        {
                            ClientId = 3,
                            Address = "88 Marina Blvd, Singapore",
                            ContactPerson = "Tan Wei Ming",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sales@aptrading.sg",
                            Name = "Asia Pacific Trading",
                            Phone = "+65 6789 1234",
                            Region = "Asia"
                        });
                });

            modelBuilder.Entity("GLMS.Models.Contract", b =>
                {
                    b.Property<int>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContractId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("ContractNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("ContractValueUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ServiceLevel")
                        .HasColumnType("int");

                    b.Property<string>("SignedAgreementPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialTerms")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ContractId");

                    b.HasIndex("ClientId");

                    b.HasIndex("ContractNumber")
                        .IsUnique();

                    b.ToTable("Contracts");

                    b.HasData(
                        new
                        {
                            ContractId = 1,
                            ClientId = 1,
                            ContractNumber = "CT-2024-001",
                            ContractValueUSD = 50000m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ServiceLevel = 1,
                            SpecialTerms = "Priority handling for all shipments",
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            ContractId = 2,
                            ClientId = 2,
                            ContractNumber = "CT-2024-002",
                            ContractValueUSD = 25000m,
                            CreatedAt = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateTime(2024, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ServiceLevel = 0,
                            SpecialTerms = "Standard terms apply",
                            StartDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2
                        },
                        new
                        {
                            ContractId = 3,
                            ClientId = 3,
                            ContractNumber = "CT-2024-003",
                            ContractValueUSD = 100000m,
                            CreatedAt = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateTime(2025, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ServiceLevel = 2,
                            SpecialTerms = "Enterprise SLA with 24/7 support",
                            StartDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        });
                });

            modelBuilder.Entity("GLMS.Models.ServiceRequest", b =>
                {
                    b.Property<int>("ServiceRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceRequestId"));

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<decimal>("CostUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostZAR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("ExchangeRateUsed")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("RequestedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpecialInstructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ServiceRequestId");

                    b.HasIndex("ContractId");

                    b.HasIndex("RequestNumber")
                        .IsUnique();

                    b.ToTable("ServiceRequests");

                    b.HasData(
                        new
                        {
                            ServiceRequestId = 1,
                            ContractId = 1,
                            CostUSD = 5000m,
                            CostZAR = 96250m,
                            Description = "Container shipping JNB to DUR",
                            ExchangeRateUsed = 19.25m,
                            RequestNumber = "SR-202401-001",
                            RequestedDate = new DateTime(2024, 1, 15, 10, 30, 0, 0, DateTimeKind.Utc),
                            Status = 3
                        },
                        new
                        {
                            ServiceRequestId = 2,
                            ContractId = 1,
                            CostUSD = 12500m,
                            CostZAR = 240625m,
                            Description = "Urgent air freight to CPT",
                            ExchangeRateUsed = 19.25m,
                            RequestNumber = "SR-202401-002",
                            RequestedDate = new DateTime(2024, 1, 20, 14, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2
                        },
                        new
                        {
                            ServiceRequestId = 3,
                            ContractId = 3,
                            CostUSD = 25000m,
                            CostZAR = 482500m,
                            Description = "Bulk cargo to Singapore",
                            ExchangeRateUsed = 19.30m,
                            RequestNumber = "SR-202402-001",
                            RequestedDate = new DateTime(2024, 2, 5, 9, 15, 0, 0, DateTimeKind.Utc),
                            Status = 1
                        });
                });

            modelBuilder.Entity("GLMS.Models.ServiceRequestLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerformedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceRequestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("LogId");

                    b.HasIndex("ServiceRequestId");

                    b.ToTable("ServiceRequestLogs");
                });

            modelBuilder.Entity("GLMS.Models.Contract", b =>
                {
                    b.HasOne("GLMS.Models.Client", "Client")
                        .WithMany("Contracts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("GLMS.Models.ServiceRequest", b =>
                {
                    b.HasOne("GLMS.Models.Contract", "Contract")
                        .WithMany("ServiceRequests")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("GLMS.Models.ServiceRequestLog", b =>
                {
                    b.HasOne("GLMS.Models.ServiceRequest", "ServiceRequest")
                        .WithMany("Logs")
                        .HasForeignKey("ServiceRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceRequest");
                });

            modelBuilder.Entity("GLMS.Models.Client", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("GLMS.Models.Contract", b =>
                {
                    b.Navigation("ServiceRequests");
                });

            modelBuilder.Entity("GLMS.Models.ServiceRequest", b =>
                {
                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
